### ISSUE TITLE
Broken docker link on landing page

### ISSUE THREAD

**Issue by toban** [wmde/wikiba.se#6]
The link to the installation page from the landing-page seems to be incorrectly pointing to https://wikiba.se/docker but should probably be https://wikiba.se/installation

**Comment by datn** [comment]
How... how did you know I was working on this at this exact moment?!

**Comment by datn** [comment]
Whoa. Anyway, yes, the target is `/install` (see source/install.md).

**Comment by datn** [comment]
https://github.com/wmde/wikiba.se/pull/7

I'm currently unable to install & build sculpin on my local to test this, but the fix is fairly clear.

**Comment by manicki** [comment]
Fixed on the live site. Thanks @datn and @toban !
